path: orig/main.dol
r13: 0x803d3740
r2: 0x803d4400
section_defs:
  text:
  - name: .init
  - name: .text
  data:
  - name: extab
    attr: a
  - name: extabindex
    attr: a
  - name: .ctors
    balign: 0
    attr: a
  - name: .dtors
    balign: 0
    attr: a
  - name: .comments
    attr: a
  - name: .rodata
  - name: .data
  - name: .sdata
  - name: .sdata2
  bss:
  - name: .bss
  - name: .sbss
  - name: .sbss2
    nobits: true
