#########################################################
# You must re-run configure.py after changing this file #
#########################################################

# Paths relative to src/
os/OSLink.c:
  .text: [0x8007136C, 0x80071d58]
  .data: [0x8010cb10, 0x8010cb60]

os/ai.c:
  .text: [0x8007eee4, 0x8007ef28]
  #.sbss: [0x803cbf78, 0x803cbfb8] 